### PR TITLE
Allow - in object key values

### PR DESCRIPTION
**Pull request by baldmountain**
A minor change to allow the dash character for object keys in input
strings.

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
:+1: cool feature :)

**Comment by rjrodger** [comment]
@baldmountain this is great, and I want to merge! Can I ask you to add a few more tests to make sure that:

* -1, -0., etc - numbers have precedence
* all variants of -*-*- work: -foo, -foo-, -foo-bar etc

thanks!

**Comment by baldmountain** [comment]
OK, I added a few more. I think I covered most likely cases.

**Comment by rjrodger** [comment]
thank you!

**Comment by baldmountain** [comment]
You're welcome! :)

**Comment by moos** [comment]
Please bump the version and publish to npm -- needing this urgently!

**Comment by AdrieanKhisbe** [comment]
:+1: :smiley:

**Pull request merged**
